# Generated by Django 4.2.6 on 2023-12-16 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PricingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dbp', models.FloatField()),
                ('dap', models.FloatField()),
                ('tmf', models.FloatField()),
                ('wc', models.FloatField()),
                ('days_of_week', models.CharField(help_text="Comma-separated list, e.g., 'Mon,Tue,Wed'", max_length=100)),
            ],
        ),
    ]
